### ISSUE TITLE
How about the accuracy of the pose estimation model on COCO dataset?

### ISSUE THREAD

**Issue by yw155** [CVBox/PyTorchCV#4]
Hi @youansheng, thanks for your great work. I would like to ask you that have you tested the accuracy of the pose estimation model on COCO dataset. If so, is it convenient to provide some evaluation results? Thanks.

**Comment by youansheng** [comment]
Have test before. I will provide some models in few days!!!

**Comment by youansheng** [comment]
You can also train the models using this project.

**Comment by NokiaDDT** [comment]
Hi, @youansheng , thanks for the great work, but I got a "nan" Loss by using this project, do you have any idea about this problem?

**Comment by youansheng** [comment]
which task?

**Comment by youansheng** [comment]
Detection now may get "nan" loss when no object exists.

**Comment by youansheng** [comment]
I'll fix it soon.

**Comment by yw155** [comment]
Hi @youansheng, providing the models is good. And could you provide the training time, training iteration numbers and the GPU number for reference? Thanks.

**Comment by CVBox** [comment]
Any GPU number is OK! The hyper parameters are defined in the json file.

**Comment by yw155** [comment]
Hi @youansheng, thank you. I just want to tune the training time according to the GPU number.

**Comment by CVBox** [comment]
You can refer to the json file.
